name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3 

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository  # Cache the Maven dependencies to speed up future builds
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Use the hash of the pom.xml to cache dependencies

    - name: Build with Maven
      run: mvn clean install  # Clean the project and build with Maven

    - name: Run Tests with Maven
      run: mvn test  # Execute the tests

    - name: Build the JAR
      run: mvn package -DskipTests=true  # Package the application into a JAR (skipping tests for packaging)

    - name: Upload JAR as an artifact
      if: success()  # Only run this step if the build was successful
      uses: actions/upload-artifact@v4
      with:
        name: my-app-jar
        path: target/my-app-1.0-SNAPSHOT.jar  # Path to the generated JAR file

