name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3

    - name: Build App with Maven
      run: mvn -B package --file pom.xml

    - name: Create multi-stage Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM maven as build
        COPY . .
        RUN mvn clean package
        FROM openjdk:17-jdk-slim as deploy
        COPY --from=build target/*.jar app.jar
        CMD java -jar app.jar
        EOF

#    - name:
#      id: build-image
#      uses: redhat-actions/buildah-build@v2
#      with:
#        image: java-app
#        tags: latest ${{ github.sha }}
#        containerfiles: |
#
          


#    - name: Login to DockerHub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Login to Github Container Registry 
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: $${{ secrets.GITHUB_TOKEN }}
 
    - name: Build with docker
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: barrype/java-app:latest

#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}

#    - name: Extract metadata for Docker tags
#      id: meta
#      uses: docker/metadata-action@v4
#      with:
#        images: ghcr.io/${{ github.repository }}

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: ${{ github.ref == 'refs/heads/master' }}
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
